[package]
name = "enhanced_rayon"
version = "0.1.1"
edition = "2021"

[dependencies]
rayon.workspace = true
num-traits.workspace = true

[features]
rng_ind_safe = []
rng_ind_unsafe = []
sng_ind_safe = []
sng_ind_unsafe = []
